services:
  grafana:
    user: root
    container_name: 'wwsheng009-saphanadb-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.1}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3088:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/wwsheng009-saphanadb-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/wwsheng009-saphanadb-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.wwsheng009-saphanadb-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: wwsheng009-saphanadb-datasource
