name: Build and Release Plugin

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Build frontend
        run: yarn run build

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Update Grafana SDK
        run: |
          go get -u github.com/grafana/grafana-plugin-sdk-go
          go mod tidy

      - name: Build backend
        run: mage -v

      - name: Package plugin
        run: |
          cd dist
          zip -r ../wwsheng009-saphanadb-datasource.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wwsheng009-saphanadb-datasource.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}